spring:
  application:
    name: impeldown
  datasource:
    url: jdbc:postgresql://localhost:5432/impeldown
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
